name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Add Flutter to PATH
        run: echo "$PATH":"$HOME/flutter/bin" >> $GITHUB_ENV    


      - name: Install dependencies
        run: flutter pub get
