name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-

      - name: Set up Flutter
        run: flutter config --no-analytics && flutter precache


      - name: Install dependencies
        run: flutter pub get
