name: Flutter Workflow

on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.10'

    - name: Get dependencies
      run: flutter pub get

    - name: Run static analysis and checks
      run: flutter analyze

    - name: Run unit tests
      run: flutter test

    - name: Run widget tests
      run: flutter test --tags "widget"

    - name: Run integration tests
      run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
